// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AffiliatesTableController from "./affiliates_table_controller"
application.register("affiliates-table", AffiliatesTableController)

import DashboardController from "./dashboard_controller"
application.register("dashboard", DashboardController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImportsController from "./imports_controller"
application.register("imports", ImportsController)

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)
