AllCops:
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "script/**/*"
    - "bin/*"

require:
  - rubocop-factory_bot
  - rubocop-rspec_rails
  - rubocop-rspec
  - rubocop-thread_safety

plugins:
  - rubocop-performance
  - rubocop-rails

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

RSpec/NestedGroups:
  Max: 4
  Include:
    - spec/requests/*.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Metrics/BlockLength:
  Exclude:
    - "config/**/*"

Style/Documentation:
  Exclude:
    - "config/application.rb"

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/modules/**/*.rb

RSpec/FilePath:
  Exclude:
    - spec/modules/**/*.rb

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/requests/**/*.rb
